name: publish-nightly
run-name: Publish nightly nupkg / ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    permissions:
      packages: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
      - name: Pack
        run: ./build.cmd pack /p:VersionSuffix=nightly.$DATE.$GITHUB_RUN_NUMBER
      - name: Push NuGet packages to GitHub
        run: |
          ./.dotnet/dotnet nuget add source https://nuget.pkg.github.com/PaulusParssinen/index.json --name github --username PaulusParssinen --password ${{ secrets.BDN_PAT }}
          ./.dotnet/dotnet nuget push **/*.nupkg -s github -k null --timeout 600
